# Generated by Django 6.0.4 on 2026-04-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
